### ISSUE TITLE
ninja STILL should have a microbomb

### ISSUE THREAD

**Issue by JoeHammad1844** [Goob-Station/Goob-Station#579]
## Description

the ninja was given a microbomb implant but it was removed after an upstream merge

**Comment by JoeHammad1844** [comment]
> death acidifier:

Not sure what you mean by this

**Comment by Piras314** [comment]
I think a death acidifier is better tbh

**Comment by JoeHammad1844** [comment]
> I think a death acidifier is better tbh

Ninjas have no allies, there is no reason for them to take an acidifer over a microbomb. the entire point of the acidifier was so nukies wouldn't TK with their microbomb

**Comment by GreyMario** [comment]
The microbomb was given to the ninja because it destroyed items on purpose and the death acidifier did not exist yet.

The ninja's job isn't to kill people. It's to achieve very specific subversion objectives and survive. The acidifier keeps ninja tech out of spessman hands should the ninja fail.

If you want to kill people for the sake of killing people, play nukie.
